# For help see the following page
# http://dev.bukkit.org/server-mods/antishare/pages/3-2-x-help/
# 
# Commands Help:
# http://dev.bukkit.org/server-mods/antishare/pages/3-2-x-help/#w-commands
# 
# Permissions Help:
# http://dev.bukkit.org/server-mods/antishare/pages/3-2-x-help/#w-permissions
# 
# Looking for a commented version of this configuration? Try here:
# https://github.com/turt2live/AntiShare/blob/master/resources/config.yml
# 
blocked-actions:
# Everything in 'blocked-actions' is a toggle for 
# turning on and off 'block-lists'. Leave these as
# true for full functionality.
  block-place: true
  block-break: true
  drop-items-on-death: true
  pickup-items: true
  drop-items: true
  right-click: true
  use-items: true
  commands: true
  combat-against-players: true
  combat-against-mobs: true
  crafting-recipes: true
  right-click-mobs: true
# Extra toggles
handled-actions:
  # Should AntiShare deal with world inventories?
  world-transfers: false
  # Should AntiShare deal with inventories for each Game Mode?
  gamemode-inventories: true
  # Ender chest support
  gamemode-ender-chests: true
# More features of AntiShare
enabled-features:
  # Set to false to NOT use AntiShare regions
  gamemode-regions: true
  # Set to false to NOT use the World Split
  world-split: true
  # Determines if creative players can gain experience
  no-experience-for-creative: true
  # Determines if you want to create per-Game Mode experience values
  change-level-on-gamemode-change: true
  # Determines if you want to create per-Game Mode balance values
  change-balance-on-gamemode-change: true
  # When true, AntiShare will not let players of some gamemode use
  # and item frame placed in another gamemode.
  disable-item-frame-cross-game-mode: true
  # Settings for attached blocks
  attached-blocks-settings:
    # True to disallow players from breaking "type1" blocks with
    # "type2" blocks attached. Eg: Survival dirt with a creative torch
    disable-breaking-mixed-gamemode: true
    # Same as above, but for placing this time. Eg: creative player can't
    # place torch on survival dirt
    disable-placing-mixed-gamemode: true
    # If the setting 'disabled-breaking-mixed-gamemode' is set as false, 
    # do you want AntiShare to break the blocks as how they were placed?
    # Example: Survival dirt with a creative torch on it, survival player
    # breaks dirt, should the torch be dropped as an item, or be broken as
    # if the player was in creative?
    break-as-gamemode: true
  # Settings for when a creative player breaks a block
  no-drops-when-block-break:
    # Clear the block's inventory (like chests)
    inventories: true
    # Remove "attached" blocks (like torches)
    attached-blocks: true
    # Consider 'paintings' (and item frames) as 'attached blocks'?
    paintings-are-attached: true
    # Count vehicles too?
    vehicles: true
    # Set to false to disable water/lava/tnt/explosion protection of creative blocks
    natural-protection: true
    natural-protection-mode: 
        deny: false
        block-drops: false
  # Mob creation settings for creative players.
  mob-creation:
    allow-snow-golems: false
    allow-iron-golems: false
    allow-wither: false
# Cooldown between game mode changes
gamemode-change-cooldown:
  # On/Off setting
  use: false
  # How long players have to wait (seconds)
  time-in-seconds: 5
# Settings
settings:
  # Set to FALSE to disable "creative" and "survival"
  # blocks.
  track-blocks: true
  # Both are the same, only commented 
  # "survival-breaking-creative".
  survival-breaking-creative-blocks:
    # Should we allow block drops?
    block-drops: false
    # Deny the break (if false, block-drops takes effect)
    deny: true
  creative-breaking-survival-blocks:
    block-drops: false
    deny: true
  creative-breaking-adventure-blocks:
    block-drops: false
    deny: true
  survival-breaking-adventure-blocks:
    block-drops: false
    deny: true
  adventure-breaking-survival-blocks:
    block-drops: false
    deny: true
  adventure-breaking-creative-blocks:
    block-drops: false
    deny: true
  # Leave as false to avoid inventory cleanup
  # WARNING: This will delete old world inventories from
  # players. If this is TRUE and your plan on using an
  # old world again, SET THIS TO FALSE.
  # If you refuse to listen to this, at least make a backup.
  # AntiShare will do as it's told, and it's developers
  # will not sympathize if you lost all your player
  # information because you were careless.
  # NOTE: This option ONLY removes the old WORLDS.
  # See the other settings to remove the old FILES
  remove-old-inventories: false
  # These settings are used to cleanup inactive players
  cleanup:
    use: true
    # Archive or delete
    method: archive
    # Days
    after: 120
  # Set to true to allow players of the same Game Mode to interact with similar
  # Game Mode objects. Such as a Creative player trying to use a Creative chest.
  # This will still not allow Survival players to use Creative blocks (like the
  # example chest)
  similar-gamemode-allow: false
# Where the magic happens.
# Here you can define EXACTLY what you want
# AntiShare to control (restrict). You can use
# key words such as "all" or "none", you can
# also use a negating character (-) to 'remove' items
# from the list (Example: "all, -dirt" = Block everything
# except dirt).
blocked-lists:
  block-place: diamond block, gold block, iron block, bedrock, tnt, emerald block
  block-break: none
  dropped-items-on-death: all
  picked-up-items: all
  dropped-items: all
  right-click: storage minecart, powered minecart, chest, furnace, dispenser, jukebox, anvil, enchantment table, ender portal frame
  use-items: fire, flint and steel, exp bottle, monster egg, egg, lava bucket, water bucket, fireball, item frame
  commands: /someCommand, /anotherCommand
  mobs: all
  right-click-mobs: all
  # To block a recipe, use the resulting item's name, such as "stick"
  crafting-recipes: all
# Splits your world in two, like 2 giant AntiShare regions
worldsplit:
  # X, Z, or None
  split: none
  # Axis value to split on
  value: 0
  # This is for any value GREATER THAN the 'value'
  positive: CREATIVE
  # This is for any value LESS THAN the 'value'
  negative: SURVIVAL
  # Warn people of the split
  warning:
    # Can be turned off
    enabled: false
    # Distance to the line
    blocks: 15
    # How many seconds should we warn each time?
    warn-every: 2
# What blocks should AntiShare track for creative and
# survival players?
block-tracking:
  tracked-survival-blocks: all
  tracked-creative-blocks: all
  tracked-adventure-blocks: all
# MagicSpells integration
magicspells:
  block-creative: true
# Misc. stuff, generally leave this alone.
other:
  debug: false
  more-quiet-shutdown: true
  more-quiet-startup: true
  stop-logblock-spam: false
  send-gamemode-change-message: true
  quiet-offline-mode-warning: false
  dont-look-for-updates: false
  use-sleep: true
  # Set to true to treat Adventure mode like Creative mode.
  # This does not affect inventories in any way (the creative
  # inventory will not become the adventure inventory)
  adventure-is-creative: true
  # Locale settings
  locale-file: locale_en_US.yml
# For when turt2live needs a copy of your configuration
error-reporting:
  error-string: TO BE DETERMINED